# Generated by Django 2.2 on 2021-02-01 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField()),
                ('additional_comment', models.TextField(blank=True)),
            ],
        ),
    ]
