# Generated by Django 2.2 on 2021-02-01 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymitem', '0001_initial'),
        ('grm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gymitem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='gymitem.Gymitem')),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='grm.Gymmember')),
            ],
        ),
    ]
