# Generated by Django 2.2 on 2021-02-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grm', '0002_rental'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Gymmember',
        ),
    ]
